name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.known-install-problems }}
    strategy:
      matrix:
        docker-folder:
        - 'Ubuntu-16.04'
        - 'Ubuntu-18.04'
        - 'Ubuntu-20.04'
        - 'Debian-8'
        - 'Debian-9'
        - 'Debian-10'
    steps:
    - uses: actions/checkout@v2
    - name: Dockerfile ${{ matrix.docker-folder }} Test
      run: docker build ${{ matrix.docker-folder }} .